### PR TITLE
Port voucher killer modules to 8.0

### PR DESCRIPTION
**Pull request by sbidoul**
invoicing_voucher_killers migrates trivially, which I confirmed with a couple of manual tests.

statement_voucher_killer is not necessary anymore since bank statements do not use vouchers in 8.0.

### CODE REVIEW

**Comment by fclementic2c** [comment]
Just a remark : invoicing_voucher_killers might become useless is oddo implement a extra functionality through the new bank reconcile widget : if the bank transaction imported match a existing move line, the bank statment line will not be posted.... It is in the pipe maybe for v8... fingers crossed

**Comment by sbidoul** [comment]
@fclementic2c I'm curious to see this feature. In any case, I think removing the "Pay" button on invoices remains a valid purpose of this module.

**Comment by guewen** [comment]
:+1:

**Comment by guewen** [comment]
@sbidoul I still see creation of a voucher in `account.payment.populate.statement` so why shouldn't we keep the override that was in `statement_voucher_killer`? See https://github.com/odoo/odoo/blob/8.0/addons/account_payment/wizard/account_payment_populate_statement.py#L96

**Comment by sbidoul** [comment]
@guewen Ah, yes, I see the voucher creation now. But it's not linked to the bank statement. 

I can't see what purpose these vouchers can serve. In my opinion, it's dead code but it does no harm. I'll check again.

**Comment by sbidoul** [comment]
I created https://github.com/odoo/odoo/issues/3023 to discuss the voucher creation issue.

**Comment by sbidoul** [comment]
@guewen the voucher creation has been removed from account.payment.populate.statement in official 8.0. 

Are there any obstacle for this PR?

**Comment by sbidoul** [comment]
Perhaps should we move invoicing_voucher_killer to OCA/bank-payment.

**Comment by guewen** [comment]
Great! It should be ok then. For the move, yes I think it makes sense.

**Comment by sbidoul** [comment]
@guewen I just did the following:
- rebased
- added a commit here to remove invoicing_voucher_killer
- created https://github.com/OCA/bank-payment/pull/68 to move invoicing_voucher_killer there

**Comment by guewen** [comment]
Thanks!

**Comment by pedrobaeza** [comment]
I merge then this "cleaning" PR.

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
