### PR TITLE
[14.0][MIG] account in payment: Migration to 14.0

### PR DESCRIPTION
**Pull request by WesleyOliveira98**
Backport #681 

cc: @marcelsavegnago @kaynnan @douglascstd

### CODE REVIEW

**Review by kaynnan — APPROVED** [review]
LGTM

**Comment by WesleyOliveira98** [comment]
ping @OCA/accounting-maintainers

**Comment by rvalyi** [comment]
cc @etobella

**Review by etobella — APPROVED** [review]

**Pull request merged**
