### PR TITLE
protect import

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can simply initialize to None, because manifest already declared external dependency.

**Comment by sbidoul** [comment]
Note that in this specific case of statement parsers, the absence of the ofx library does not prevent Odoo to start: it simply displays an error in the log file. So this specific PR is probably not necessary.

**Comment by sbidoul** [comment]
Oops. Forget my previous comment. I thought we were on the 8.0 branch.

**Review by pedrobaeza — APPROVED** [review]
This old one is correct and this shouldn't harm the Travis status. @gurneyalex, if you rebase, we can see.

**Comment by gurneyalex** [comment]
@pedrobaeza rebased.

**Comment by pedrobaeza** [comment]
As branch is red, we can simply merge this old one.

**Pull request merged**
