### PR TITLE
[15.0][MIG] account_bank_statement_reopen_skip_undo_reconciliation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by alvaro-domatix — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@MiquelRForgeFlow could you rebase, please?

**Comment by MiquelRForgeFlow** [comment]
@HaraldPanten done

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM. Tested in runboat

**Pull request merged**
