### PR TITLE
[ADD] account_reconcile_reconciliation_date

### PR DESCRIPTION
**Pull request by osi-scampbell**
This PR adds account_reconcile_reconciliation_date to the OCA/account-reconcile repo. See issue #294

### CODE REVIEW

**Comment by max3903** [comment]
@osi-scampbell LGTM but it's missing documentation and unit tests

**Review by max3903 — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@osi-scampbell What about partial reconciliations? If you create two payments for the same invoice? As I understand the field in the invoice would show only the date of the last payment.

**Comment by max3903** [comment]
Hello @JordiBForgeFlow That's the requirement. @patrickrwilson may confirm.

**Pull request merged**
