### PR TITLE
[14][FIX] (fix the previous PR #420) account_reconcile_widget: value cleaning & decimal separator choice

### PR DESCRIPTION
**Pull request by TeoGoddet**
Fix PR #420

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Pre-commit error

**Comment by TeoGoddet** [comment]
Ok, pre-commit is removing the slash, that's why the PR has an error, i'm very sorry for this.
I'm investigating

**Comment by TeoGoddet** [comment]
Prettier is causing the problem, i'm investigating more
@pedrobaeza I suggest that you merge this so that the branch doesn't stay with the error

**Comment by pedrobaeza** [comment]
We can't merge with the red CI

**Comment by pedrobaeza** [comment]
I can revert your initial commit if you prefer

**Comment by TeoGoddet** [comment]
Ok, 
prettier is pretty hard do debug
easiest fix I see is replacing \d by 1-9

**Comment by pedrobaeza** [comment]
Didn't you need double backslash (`\\`)?

**Comment by TeoGoddet** [comment]
Indeed, 
sorry for all this noise,

**Pull request merged**
