### PR TITLE
[10.0][ADD] account_payment_mode_auto_reconcile

### PR DESCRIPTION
**Pull request by grindtildeath**
Supersedes: https://github.com/OCA/bank-payment/pull/618

### CODE REVIEW

**Comment by grindtildeath** [comment]
@TDu @i-vyshnevska @tschanzt @jcoux @sebalix Can you guys please update your reviews from former PR here?

**Review by Tonow-c2c — APPROVED** [review]
Code review only

**Review by mmequignon — APPROVED** [review]

**Pull request merged**
