### PR TITLE
Restore 8.0 were it was replaced wrongly

### PR DESCRIPTION
**Pull request by yvaucher**
This has been removed automatically but we want 8.0 here not 9.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The migration script makes a blindly replace, so that's why it has this value. You can replace 8.0 by 8 without losing meaning, and thus, we avoid future replacements. for version 10 and so on.

**Comment by yvaucher** [comment]
@pedrobaeza I disagree to replace dumbly all 8.0 by 8. By the way it won't change for version 10.0 as we will be looking on 9.0. And by the way 7 is named 7.0 below

**Comment by pedrobaeza** [comment]
OK, you're right about that appreciation that on v10 migration this won't change. OK for me.

**Comment by StefanRijnhart** [comment]
Trivial, no? :+1:

**Comment by yvaucher** [comment]
@StefanRijnhart Yup just did a PR to make a trace to warn it might have to be fixed in other repo

**Pull request merged**
