### PR TITLE
Add history line + error message if reconciliation fails

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to add an history line + a mail thread to easy reconciliation tasks. The reason is that the current cron can "loop" on a task since it takes the one with the oldest history, and no history was added in case of error.

I also added the error message in order to get basic logging on it.

### CODE REVIEW

**Comment by fclementic2c** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
The Runbot failed on another module.

**Comment by sbidoul** [comment]
One test fails due to missing 2014 period. Can you fix it?

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
It is indeed another module that fails. We will address it separately.

**Comment by lepistone** [comment]
Thinking about @sbidoul's comment, maybe he is right: the history line is for users and should help to understand if there is a functional problem. On the other hand, we are suppressing the stack trace that would be logged without this try/except. If it is that way, probably yes, it would be good to `logger.exception` the stacktrace.

Another thing: could it be that a DB error leaves a broken cursor so that we don't manage to write our history line?

**Comment by lepistone** [comment]
PS I understand this is a somewhat urgent bugfix: ping me for an approval+merge once it's ready.

**Comment by lepistone** [comment]
For the red build I opened #80.

**Comment by mdietrichc2c** [comment]
@sbidoul @lepistone thanks for the feedback, I added the stack trace in the latest commit.

**Comment by sbidoul** [comment]
:+1:

**Comment by lepistone** [comment]
Thanks @mdietrichc2c.

As for the other point I raised, it is probably enough to log the trace in that case. To be on the safe side, I'd put the `_logger.exception` line right after `except`.

Done that, I'll merge it. Thanks!

**Comment by mdietrichc2c** [comment]
@lepistone done

**Comment by lepistone** [comment]
ok, only the failure we know about. :+1:

**Pull request merged**
