### PR TITLE
[ADD] account_reconcile_different_partners

### PR DESCRIPTION
**Pull request by hbrunn**
# Reconcile move lines from different partners

While it is in general not a good idea to reconcile move lines from different partners, there can be situations where this is not avoidable. This module allows you to do that.
# Configuration

By default, only finance managers are allowed to reconcile different partners' move lines. If you need other people to do that, add them to the group _Technical/Reconcile different partners' move lines_.
# Known issues / Roadmap
- enforcing the same partner for reconciliation avoids mistakes, so assign this group only to people who know what they are doing
- it would be nice to have warnings when selecting different partners

### CODE REVIEW

**Comment by fclementic2c** [comment]
:-1: 

Sorry but I have a big problem with that.
This feature is not compatible with the webkit financial reports (you will have differences between partner ledger report and partner balance).

**Comment by hbrunn** [comment]
so much worse for that module I'd say. You are aware that different partners in opening periods are allowed by odoo standard?

**Comment by sbidoul** [comment]
@brunn I agree with @fclementic2c here. When reconciliations between different partners must occur, it can and must be done on accounts that are not of type payable/receivable.

Regarding the opening periods, the self reconciliation that occurs there is just a technical side-effect of the way opening entries work in Odoo, and IMO must not be extended to other situations.

**Comment by hbrunn** [comment]
@sbidoul "[...] must be done on accounts that are not of type payable/receivable" is this a local juristical issue or a technical one?

**Comment by sbidoul** [comment]
@hbrunn ~~sorry, I should have written "_can_ be done on accounts that are not of type payable/receivable".~~

If you mix partners in reconciliations on receivable/payable accounts, you could get an Open Invoices report that shows nothing for such partner (because all reconciled) while the Partner Balance report would show non zero amounts for such partners. Not desirable IMO.

**Comment by pedrobaeza** [comment]
@hbrunn is this still needed? There are question without answers, so I tend this to close it.

**Pull request closed without merging**
