### PR TITLE
[13.0][MIG] account_reconcile_model_strict_match_amount

### PR DESCRIPTION
**Pull request by grindtildeath**
Migrated from: 
 - [ ] https://github.com/OCA/account-reconcile/pull/302

Requires:
 - [x] https://github.com/odoo/odoo/pull/50413

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by ajaniszewska-dev** [comment]
@grindtildeath  pre-commit...

**Review by i-vyshnevska — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@grindtildeath pls squash

**Comment by grindtildeath** [comment]
@simahawk done ;)

**Comment by simahawk** [comment]
@grindtildeath sorry for being nit-picking but last 2 commits can staty w/ previous one or at least have the module name in the msg?

**Pull request merged**
