### PR TITLE
[17.0][MIG] account_statement_base: Migration to 17.0

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the PR title renaming. You just have missed the underscores on the module name. I have just put them.

/ocabot migration account_statement_base

**Comment by rov-adhoc** [comment]
@pedrobaeza Hi Pedro! I would like to ask you if there is something missing in this PR in order to be merge it. Thanks in advance! Best regards!

**Comment by pedrobaeza** [comment]
Reviews: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

You can review other PRs, and ask in exchange they review yours.

**Comment by StefanRijnhart** [comment]
Can you check the warning that Odoo emits on installation of the module?
```
2023-12-15 16:14:37,845 230 INFO odoo odoo.modules.loading: Loading module account_statement_base (40/43) 
2023-12-15 16:14:37,966 230 WARNING odoo py.warnings: /opt/odoo/odoo/addons/base/models/ir_module.py:170: DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, account_statement_base can just have a UTF8 description with not need for a declaration.
```

**Comment by StefanRijnhart** [comment]
Oh, fixed here I see. https://github.com/OCA/maintainer-tools/issues/595

**Review by StefanRijnhart — APPROVED** [review]

**Review by norlinhenrik — APPROVED** [review]
LGTM (I installed it and opened a statement and one of its lines in form view.)

**Pull request merged**
