### PR TITLE
Fixed the reconciliation widget

### PR DESCRIPTION
**Pull request by tosink**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Closed by accident, but you must try on local first and then push only one commit. And explain what is the problem.

**Comment by tosink** [comment]
I fixed this issue: https://github.com/OCA/account-reconcile/issues/429

**Comment by tosink** [comment]
I fixed this issue: https://github.com/OCA/account-reconcile/issues/429

**Comment by tosink** [comment]
> Closed by accident, but you must try on local first and then push only one commit. And explain what is the problem.

Please I have signed the OCA . Can this be approved? [pedrobaeza](https://github.com/pedrobaeza)

**Comment by pedrobaeza** [comment]
What is the problem?

**Comment by tosink** [comment]
we need this commit approved

**Comment by pedrobaeza** [comment]
And I need to know what is the problem that is fixing, and you have to pass pre-commit and Travis, and let only one commit.

**Pull request closed without merging**
