### PR TITLE
Make unit tests use the current year

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to fix https://github.com/OCA/bank-statement-reconcile/issues/80 .

### CODE REVIEW

**Comment by lepistone** [comment]
Can you please `commit --amend` and write `Fixes #80` in the commit message? Otherwise :+1:

**Comment by mdietrichc2c** [comment]
@lepistone done

**Comment by guewen** [comment]
:+1:

**Comment by tafaRU** [comment]
:+1:

**Comment by lepistone** [comment]
:triangular_flag_on_post: the build is actually red, can you investigate @mdietrichc2c?

**Comment by lepistone** [comment]
I gave a look to the red build, and IMO it is an unrelated problem in another module. So I'm going to merge this one as soon as we have a third thumbs-up.

**Comment by gurneyalex** [comment]
:+1: looks good to me

**Pull request merged**
