### PR TITLE
[IMP] account_reconcile_oca: Fix multicurrency journal management

### LINKED ISSUE #656: [16.0] account_reconcile_oca: problem on bank account in foreign currency
## account_reconcile_oca

Here is a scenario to reproduce the bug on v16:
1. I have a company with currency = EUR
2. I create a bank journal in currency USD
3. the last EUR/USD exchange rate is dated yesterday with rate = 1.15 € for 1 USD
4. I import the bank statement in USD. I have 1 bank statement line of 1000 USD dated today. Odoo create the account.move.line with amount_currency=1000.0, currency_id=USD and debit/credit = 1150 EUR

at that stage, if I start the bank statement reconcile interface, I get this:

bank_statement_before_rate_up

6. the currency rate update cron is executed in the afternoon after the publication of the daily rates by the European Central Bank ; the USD/EUR rate for today becomes 1.20 € (it's an example !)
7. I start the OCA reconcile interface for the bank statement: I get this:

account_reconcile_oca-after_rate

It shows an amount of 958,33 $... instead of 1000 $ !

When I look at the code here:
https://github.com/OCA/account-reconcile/blob/16.0/account_reconcile_oca/models/account_reconcile_abstract.py#L36
I can see that vals['currency_amount'] is recomputed on the fly from debit/credit using the exchange rate. If I hack that code in the "else" to have amount = line.amount_currency, then I get this:

hack

with credit = 1200 € with the value 1150 € of the account.move.line which is crossed out.
I don't understand the logic of the code of account_reconcile_oca on bank journals in foreign currency. I would love to help on this, but I need to understand the design decision for this scenario, to be able to propose a patch.

### PR DESCRIPTION
**Pull request by etobella**
The main idea of this commit is to show the right currency amount

Should fix #656

@alexis-via

### CODE REVIEW

**Comment by etobella** [comment]
@PaulGoubert

**Comment by PaulGoubert** [comment]
LGTM @etobella    Thank you very much for your support.

**Review by PaulGoubert — APPROVED** [review]

**Review by PaulGoubert — COMMENTED** [review]
Some issues persist and prevent proper matching. I discussed it with Alexis yesterday, and he will provide you with a detailed report of the problems we identified. Thank you again for your help.

**Comment by etobella** [comment]
If we can have the exact detail, I can construct the test in order to avoid future regressions :wink:

**Comment by etobella** [comment]
@alexis-via @PaulGoubert Can you test again? I made a lot of changes in order to change all the stuff, but tests are passing and I added a new test with your case (I would like to add some more in order to ensure that all works fine)

**Comment by josselin-arica** [comment]
Hola, se esta presentando una observación ya que al momento de conciliar no esta trayendo el importe en moneda, les pasa lo mismo?

**Comment by etobella** [comment]
@josselin-arica there is a lot of people in this conversation that doesn't speak Spanish. Only on the localization repos you could do that.

Can you send a complete flow of your problem in order to see what happens? You should test in the runbot in order to ensure that it is not a problem of your installation

**Comment by josselin-arica** [comment]
Hola estoy probando el módulo en una base nativa (test) y sucede lo siguiente:

1. He creado un diario con moneda USD 
2. He creado una cuenta en USD para que actúe como contrapartida a la hora de conciliar.
3. Al momento de conciliar en diario USD creado, y elegir esta cuenta me aparece un mensaje "La cuenta seleccionada en tu asiento diario obliga a proporcionar una moneda secundaria. Debes eliminar la moneda secundaria de la cuenta" 
4. Ese mensaje me aparece siempre que use USD, sin embargo en caso logre conciliar ya que es un mensaje espontaneo, cuando ingreso al asiento contable de la conciliación, en la columna importe en moneda (que esta oculta) no trae el importe.
Les pasa lo mismo?

**Comment by etobella** [comment]
@josselin-arica in english please. The first time I answered and explained that you should ask and comment in english.

**Comment by josselin-arica** [comment]
Hello, I am testing the module on a native basis (test) and the following happens:

I have created a journal with USD currency
I have created an account in USD to act as a counterparty when reconciling.
When I reconcile in the USD journal created, and choose this account, I get a message "The account selected in your journal entry requires you to provide a secondary currency. You must delete the secondary currency from the account"
This message appears whenever I use USD, however, if I manage to reconcile since it is a spontaneous message, when I enter the reconciliation accounting entry, in the currency amount column (which is hidden) it does not show the currency amount.

Does the same thing happen to you?

**Comment by etobella** [comment]
Did you test this PR or the latest merged version? @josselin-arica

**Comment by etobella** [comment]
Well, I needed to do a lot of changes in order to make it work properly.

The main issues is that Odoo was already calculating the exchange rate and this was confusing (also, Odoo ignores the rate we set in order to compute it). I solved it by keeping the logic from Odoo

@legalsylvain @PaulGoubert

**Comment by PaulGoubert** [comment]
> Well, I needed to do a lot of changes in order to make it work properly.
> 
> The main issues is that Odoo was already calculating the exchange rate and this was confusing (also, Odoo ignores the rate we set in order to compute it). I solved it by keeping the logic from Odoo
> 
> @legalsylvain @PaulGoubert

@alexis-via

**Comment by alexis-via** [comment]
I tested the scenario described in my bug report and it now works well ! Thank you @etobella !

I continued with a similar multi-currency scenario and I found another problem. Here is the detailed scenario:

1) I have a company with currency = EUR
2)  I create a bank journal in currency USD
3) On the USD currency, I create 3 different rates:
- D-2 (the day before yesterday): rate = 1.10 € for 1 USD
- D-1 (yesterday) : rate = 1.15 € for 1 USD
- D (today) : rate = 1.20 € for 1 USD
4) I create a vendor bill for partner Ready Mat  of 1000 $ dated D-2
5) I create a vendor bill for partner Ready Mat  of 1000 $ dated D-1
6) I create a bank statement line of -2000$ in my USD bank journal for partner Ready Mat dated D. I link it to the 2 invoices. I get this:

bug42

The problem is that I still have the line in the Bank suspense account of 0,01 €.

**Comment by etobella** [comment]
The same happens with EE 
image

This probably comes from differences of decimals when transforming from USD to EUR and EUR to USD... IMO this case implies that the user needs to define the difference manually

**Comment by etobella** [comment]
@alexis-via If you approve it, we can proceed with merge and I will port it to 17 :wink:

**Comment by pleirb** [comment]
Hello, how are you all!

Same situation as @alexis-vía, with notes in foreign currency trying to reconcile in a bank account also in foreign currency, apparently everything is going well:
imagen
But when validating the reconciliation something strange happens, look how the counterparts change:
imagen

On the other hand, if for some reason, the base currency amount differs like in this example:
imagen
When validating I receive this error:
```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1632, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1659, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1863, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/auto/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 6609, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 6320, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/auto/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 205, in _onchange_add_account_move_line_id
    reconcile_auxiliary_id, lines = self._get_reconcile_line(
  File "/opt/odoo/auto/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 874, in _get_reconcile_line
    reconcile_auxiliary_id, rate = self._compute_exchange_rate(
  File "/opt/odoo/auto/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 920, in _compute_exchange_rate
    "account_id": account.name_get()[0],
IndexError: list index out of range

The above server error caused the following client error:
null
```

**Review by aritzolea — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it.

/ocabot merge major

Please fw-port it to 17.

**Pull request merged**
