### PR TITLE
[16.0][IMP] account_reconcile_oca: Several improvements

### PR DESCRIPTION
**Pull request by etobella**
This includes:
- [x] fix on kanban view with big screens
- [x] Aggregation of lines by statement
- [x] Aggregation of statements by date (shows date, but not amount on the period)
- [x] show a total balance

@vdewulf I think you will like this one :smile: 

image

### CODE REVIEW

**Review by flotho — APPROVED** [review]
functionnal review on riunboat OK
Thanks for this.
LGTM

**Comment by flotho** [comment]
hi @etobella thanks for your improvements.
As a proposal / Question for another PR, could it make any sense to have this kind of aggregation per journal ? Most of times when working with multiple accounts you have an account with a lot of moves and others working basically on monthly/yearly basis. Agregation needs won't be the same .
Anyway your actual improvements are awesome !

**Comment by etobella** [comment]
The aggregation is set by company but you can change the behavior in an specific journal :wink: 

It was already done this way

https://github.com/OCA/account-reconcile/pull/662/files#diff-2e995afb60e7a1f8ff55fe7f44da038a15a7caae4a3c7c529503016448ac9701R16-R25

**Comment by flotho** [comment]
thanks for those precisions! 
Regards

**Comment by etobella** [comment]
@JordiMForgeFlow :wink:

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review

**Pull request merged**
