### PR TITLE
[FIX] account_reconcile_oca: Fix foreign currency

### LINKED ISSUE #622: [16.0] account_reconcile_oca currency exchange valuation handling issues
## Module
account_reconcile_oca

## Describe the bug
Currency exchange rates have trash (delete) icon and when clicked new currency exchange lines are created.

## To Reproduce
**Affected versions**: 16.0

1. Create an invoice other than the company currency and confirm
2. Create an operation and try to reconcile it with the invoice created in 1
3. Click on the trash icon at the end of the currency rate difference line 
or click on statement line 
or click on invoice line. 
4. If you try to delete these lines more pops up

**Expected behavior**
Currency exchange difference lines shouldn't have delete option and clicking on lines shouldn't bring new lines.

**Additional context**
There are screenshots of this bug here in this PR:

https://github.com/OCA/account-reconcile/pull/587#issuecomment-1711767810

@etobella  thanks

### PR DESCRIPTION
**Pull request by etobella**
This should fix #622

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@etobella can this be the same problem I fixed in #633 for 15.0?

**Comment by etobella** [comment]
Seems similar because the concept is related, but at the end is different, Javascript was recreating the difference amount. and it was created severall times. However, after viewing your error, I would do an extra improvement to create just one (overwrite it if necessary)

**Comment by lk-eska** [comment]
LGTM

**Review by oihane — APPROVED** [review]
LGTM

**Comment by anajuaristi** [comment]
👍 LGTM

**Pull request merged**
