### PR TITLE
[15.0][MIG] account_reconcile_restrict_partner_mismatch: Migration to 15.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago 

#408

### CODE REVIEW

**Comment by kaynnan** [comment]
ping @OCA/accounting-maintainers

**Comment by marcelsavegnago** [comment]
@augustodinizl @aug1804 Can you do the functional review please?

**Review by grindtildeath — APPROVED** [review]
LGTM, thx for the mig :+1:

**Review by sbejaoui — APPROVED** [review]
Code review

**Comment by grindtildeath** [comment]
/ocabot migration account_reconcile_restrict_partner_mismatch

**Pull request merged**
