### PR TITLE
[12.0][MIG] account_mass_reconcile_ref_deep_search

### PR DESCRIPTION
**Pull request by i-vyshnevska**
fixes for test laying in https://github.com/OCA/account-reconcile/pull/275

### CODE REVIEW

**Review by grindtildeath — COMMENTED** [review]
Tests are failing :(

**Comment by i-vyshnevska** [comment]
> Tests are failing :(

as I said in description fix for this PR in https://github.com/OCA/account-reconcile/pull/275

**Review by tschanzt — APPROVED** [review]

**Comment by grindtildeath** [comment]
@i-vyshnevska I guess you meant https://github.com/OCA/account-reconcile/pull/276

**Review by jcoux — APPROVED** [review]
Seems good technically (if check become green).

**Comment by jcoux** [comment]
@grindtildeath Yes, fixes done into https://github.com/OCA/account-reconcile/pull/275 are included into https://github.com/OCA/account-reconcile/pull/276

**Comment by grindtildeath** [comment]
Same as for #276, I'm not sure if this is still needed after #292

**Comment by mmequignon** [comment]
Haven't tested it, but code looks good.

**Review by mmequignon — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
