### PR TITLE
add partial_reconcile option to allow to remove partial reconcile

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
Hello,

following my comment on #43 I propose this commit with a new option : 'partial_reconcile' to allow to remove partial reconcile.

### CODE REVIEW

**Comment by guewen** [comment]
@vrenaville @fclementic2c any opinion?

Technically ok, but the help on the field should be improved, because it concerns only `manual` partial reconcile, the other ones are already removed.

**Comment by laetitia-gangloff** [comment]
@guewen I think it concerns all partial reconcile (at moment of the PR).
In my use case we use only automatic reconciliation, and partial reconciliation was not unreconciled, and this is the reason of this PR.

**Comment by guewen** [comment]
Isn't the following line in #44 there for that reason:

```
 "AND COALESCE(account_move_reconcile.type,'') <> 'manual' "
```

Anyway, automatic partial reconciliation must always be unreconciled, if it is not the case, it is a bug.
I see an interest in this option only if it concerns the manual partials, when the automatic are always retried.

**Comment by laetitia-gangloff** [comment]
For partial reconcile, the type is always set to 'manual' :
https://github.com/OCA/bank-statement-reconcile/blob/7.0/account_easy_reconcile/base_reconciliation.py#L237

**Comment by guewen** [comment]
> For partial reconcile, the type is always set to 'manual' :
> https://github.com/OCA/bank-statement-reconcile/blob/7.0/account_easy_reconcile/base_reconciliation.py#L237

I see now! I think that's what is wrong. I think they should be 'auto', so partial reconciles created manually are kept and the ones created by the auto-reconcile are unreconciled. What do you think?

**Comment by vrenaville** [comment]
@laetitia-gangloff I think that we need to preserve "real" manual partial reconcile.
I think that we need to correct this bug before:  https://github.com/OCA/bank-statement-reconcile/blob/7.0/account_easy_reconcile/base_reconciliation.py#L237 
all reconcile full or partial done automatically need to be set to "auto".

**Comment by laetitia-gangloff** [comment]
I will change this 'manual' to 'auto'. I think, it will correct my initial problem. 
Then, I think, this PR, can be closed.

**Comment by vrenaville** [comment]
@laetitia-gangloff Thanks for your response, your PR on the change from manual to auto will be appreciated ;)

**Comment by fclementic2c** [comment]
:+1:

**Pull request closed without merging**
