### PR TITLE
[FIX] Prevent remove partial reconcile, when you use easy reconcile

### LINKED ISSUE #43: Automatic reconcile delete and replace some partial reconcile done by user manually
Automatic reconcile delete and replace some partial reconcile done by user manually

To reproduce:
- Create a customer invoice for 10000 € to Customer X (customer account: 4110000) - Add a reference : ABC1234 and validate the invoice to book it into ledger
- Pay partialy that invoice (8000€) using the bank statement...but fill in a different reference (XYZ789) - Confirm the bank statement - the payment entry will be posted.
- Reconcile manually the invoice and the partial payment
- Create a new bank statement to record a 2nd partial payment for that invoice (1500€) but this time the reference is the same than the one use on the invoice entry (ABC1234) .
- Lauch the automatic reconcile on the receivable account

The bug is the following:
- The system will create a partial reconcile between the invoice and 2nd payment without including the 1st payment done manualy reconciled (because this one do not have the same reference).
- the initial partial reconcile is broken because linked to only 1 account move line (the other one being now reconciled with the 2nd payment)

### PR DESCRIPTION
**Pull request by vrenaville**
Fixes #43

### CODE REVIEW

**Comment by vrenaville** [comment]
It 's pending for the fix #45

**Comment by pedrobaeza** [comment]
You can rebase now that #45 is merged.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
:+1: thanks

**Pull request merged**
