### PR TITLE
[17.0][IMP] account_statement_base + account_reconcile: Forward port missing commits

### PR DESCRIPTION
**Pull request by etobella**
This PR adds several commits from this two modules

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check several commits that are not relevant, like the pre-commit one only modifying tr.po

**Comment by etobella** [comment]
The only non-relevant commits that don't come from 16.0 are `[FIX] account_mass_reconcile: Fix pre-commit issue` and `[FIX] account_reconcile_oca: Remove warning`. First one is necessary in order to avoid an error on pre-commit but it is not related to any of this modules. Actually, 17.0 branch pre-commit is failing https://github.com/OCA/account-reconcile/actions/runs/10366738074/job/28696666245... Should I create an specific PR for that?
The second one was removing a warning on pre-commit, but I can remove it.

**Review by pedrobaeza — APPROVED** [review]
OK then

**Review by cvinh — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@etobella there are conflicts. Can you solve then?

**Pull request merged**
