### PR TITLE
[10.0][Backport] account_set_reconcilable

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Backport of https://github.com/OCA/account-reconcile/pull/220.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@mreficent travis screams

**Comment by MiquelRForgeFlow** [comment]
The v10 branch is broken

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: It works fine as in v11.

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
