### PR TITLE
[14.0][FW] account_mass_reconcile: port from 12.0

### PR DESCRIPTION
**Pull request by kv1612**
Depends on:
- https://github.com/OCA/account-reconcile/pull/371

Port PR from 12.0:
- https://github.com/OCA/account-reconcile/pull/353

### CODE REVIEW

**Comment by tv-openbig** [comment]
After successfull installation and follwing the path
'Invoicing / Accounting / Mass Automatic Reconcile' and click on "Create" button to start a new mass
reconcile i get a error message:

Error:

Traceback:
TypeError: Cannot read properties of undefined (reading 'colspan')
    at http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2264:34
    at Array.forEach (<anonymous>)
    at Class._renderInnerGroup (http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2263:75)
    at Class._renderTagGroup (http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2279:248)
    at Class._renderNode (http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2271:244)
    at Class._renderNode (http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:5922:13)
    at Class._renderNode (http://192.168.201.155:8069/web/content/246-537b526/web.assets_common.js:4648:371)
    at Function._.map._.collect (http://192.168.201.155:8069/web/content/246-537b526/web.assets_common.js:109:270)
    at Class._renderTabPage (http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2277:661)
    at http://192.168.201.155:8069/web/content/278-6268b37/web.assets_backend.js:2286:380


Bildschirmfoto 2022-01-14 um 13 55 11

**Comment by kv1612** [comment]
Hi @tv-openbig, my typo, sorry about that. This PR has been updated. Thank you.

**Comment by tv-openbig** [comment]
> Hi @tv-openbig, my typo, sorry about that. This PR has been updated. Thank you.

Hello @kv1612 Now i was able to install it on v14.
However i have detected an issue or maybe it is a misusage of myself.
Please check my video here: https://drive.google.com/file/d/1_jsf5L0fWUj7o5nNovD3DoNu5nJl7iO0/view

I have created a customer invoice with a total amount of 116.00
Then i have partially reconciled with a payment amount of 115.95.
Now i want to mass reconcile the difference of 0.05 Cent, which doesn't work as expected.

**Comment by hailangvn** [comment]
Good day @tv-openbig, thanks for your testing and recording. Here are couple of reasons why it didn't work.
* The reference of `Simple. Amount and Reference` is actually `Bill Reference` in Vendors > Bills. In the video, Customers > Invoices is `Payment Reference` instead so it is first reason.
* Mass Reconcile finds journal items those are not reconciled and then try to match them together. In the video, the invoice has green `PARTIAL` strip at top left corner. It means its journal items are already reconciled so it is second reason.

Could you please try again below steps?
1. Create Vendors > Bills with `Bill Reference`. Do not use `Register Payment` button as it will reconcile.
2. Go to Vendors > Payments and create new payment and put the reference of step 1 in `Memo`.
3. Perform the mass reconcile action.

**Comment by tv-openbig** [comment]
> Good day @tv-openbig, thanks for your testing and recording. Here are couple of reasons why it didn't work.
> 
> * The reference of `Simple. Amount and Reference` is actually `Bill Reference` in Vendors > Bills. In the video, Customers > Invoices is `Payment Reference` instead so it is first reason.
> * Mass Reconcile finds journal items those are not reconciled and then try to match them together. In the video, the invoice has green `PARTIAL` strip at top left corner. It means its journal items are already reconciled so it is second reason.
> 
> Could you please try again below steps?
> 
> 1. Create Vendors > Bills with `Bill Reference`. Do not use `Register Payment` button as it will reconcile.
> 2. Go to Vendors > Payments and create new payment and put the reference of step 1 in `Memo`.
> 3. Perform the mass reconcile action.

@hailangvn

Hello, i could not recapture mass recociliation with vendor bills:
https://drive.google.com/file/d/1s-AJ_MW8qrdU3Op_Vmcv_W6v6BdmMiiV/view

**Comment by hailangvn** [comment]
To match `Label` column, please use `Mass Reconcile Simple Name` type instead of `Mass Reconcile Simple Reference` type. The later type matches `Reference` column. You can show `Reference` column by clicking three dots button at right of table header as in screenshot.
image

**Comment by tv-openbig** [comment]
> To match `Label` column, please use `Mass Reconcile Simple Name` type instead of `Mass Reconcile Simple Reference` type. The later type matches `Reference` column. You can show `Reference` column by clicking three dots button at right of table header as in screenshot. image

@hailangvn Thanks a lot for your advise. Now i could recapture your proposal. By changing the type my example works. It works both with debitors as well witjh creditors.

**Pull request closed without merging**
