### PR TITLE
[14.0][FIX] account_mass_reconcile: fix tests

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Otherwise the current tests will fail in any other PR.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Hey! @grindtildeath I am trying to greenify the repo, but I'm getting an error in the module account_mass_reconcile_as_job. See https://github.com/OCA/account-reconcile/actions/runs/5210490714/jobs/9401635456?pr=551#step:8:330. I am not familiar with this model. Can you help me?

**Comment by florian-dacosta** [comment]
@JordiBForgeFlow Must be due to that : https://github.com/OCA/queue/pull/537

I guess here : https://github.com/OCA/account-reconcile/blob/14.0/account_mass_reconcile_as_job/tests/test_scenario_reconcile_as_job.py#L47 we should test the specific recordset on which the job apply :             
```
trap.assert_enqueued_job(
                self.env["account.mass.reconcile"].reconcile_as_job,
                args=(),
            )
```
Would become : 
```
trap.assert_enqueued_job(
                mass_rec.reconcile_as_job,
                args=(),
            )
```

Same here : https://github.com/OCA/account-reconcile/blob/14.0/account_mass_reconcile_as_job/tests/test_scenario_reconcile_as_job.py#L93

You can see the same kind of fix here for instance : 
https://github.com/OCA/server-tools/pull/2646

Hope it helps

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Thanks @florian-dacosta !!

**Pull request merged**
