### PR TITLE
Overloaded method onchange_type had an extra argument without default value

### PR DESCRIPTION
**Pull request by ghost**
Added fefault value for argument profile_id, and cleaned a PEP8 issue.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think it's better to just make profile_id a keyword argument, instead of having a new method.

**Comment by ghost** [comment]
<Odoo 7 addon>account/account_bank_statement.py:529
The function signature is def onchange_type(self, cr, uid, line_id, partner_id, type, context=None):

The osv considers this to be the valid signature for the function when using a view onchange property. Because of that, the additional argument is consider to be the context (as it doesn't accepts keyword arguments in a view's XML), instead of the new argument.

In this case it is better to have a new method, for those views that can offer the extra argument, and delegate the call to this new method when a call to the old method is done.

**Comment by pedrobaeza** [comment]
I still think a keyword argument works better. You can call it the old or the new way, and treat inside testing for None for profile_id value.

**Comment by ghost** [comment]
During our test, Odoo consider the extra argument to be the context, and view's XML don't accept arguments by keyword.

**Comment by pedrobaeza** [comment]
It can be if you call it correctly with keyword argument:

```
def onchange_type(self, cr, uid, line_id, partner_id, type, profile_id=None, context=None):
    res = super(X, self).onchange_type(cr, uid, line_id, partner_id, type, context=context)
```

**Comment by ghost** [comment]
I repeat, the problem is in the onchange property of a form view XML.

**Comment by pedrobaeza** [comment]
But you're overwriting that onchange property in all places...

I still don't understand the problem, but I let others to bring clarity to this, because maybe I'm wrong.

**Comment by pedrobaeza** [comment]
As there's no answer in this, I think we can close this.

**Pull request closed without merging**
