### PR TITLE
In account_easy_reconcile, now write-off entries can be created with an analytic account

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by lepistone** [comment]
Ported from Launchpad

https://code.launchpad.net/~camptocamp/banking-addons/bank-statement-reconcile-7.0-account_easy_reconcile-analytic-account/+merge/213007

**Comment by lepistone** [comment]
Already approved 3 times on launchpad (+ me). Thanks

**Comment by pedrobaeza** [comment]
As it has the three approvals, I proceed with the merge

**Comment by pedrobaeza** [comment]
You have been faster ;)

**Pull request merged**
