### PR TITLE
[15.0][MIG] account_reconcile_widget: Migration to 15.0

### PR DESCRIPTION
**Pull request by kelvzxu**

### CODE REVIEW

**Comment by kelvzxu** [comment]
i got this error in runbot community. does anyone know how to solve this problem

"Unable to find image 'oca-account-reconcile:c0e4270_env_1_job_1' locally
docker: Error response from daemon: pull access denied for oca-account-reconcile, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'."

**Comment by jcdrubay** [comment]
@ Maintainers:
Is it possible to restart a build with runboat?
Thanks

**Comment by jcdrubay** [comment]
Hi @kelvzxu, 

it seems that your commit history does not meet the requirements described in 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

Are you still working on this upgrade?

**Comment by kelvzxu** [comment]
ok I will make adjustments according to standard. this is because
there is no explanation for migrating to 15.0

**Comment by jcdrubay** [comment]
Indeed there was a lack of documentation at the time you did the migration because you did it very early.

We did some quick tests and it seems to work well.

Thanks for your work, I will try to help you pass all the steps to get you migration work merged :)

**Comment by pedrobaeza** [comment]
Well, the migration issue was created the 17th of October and this was proposed on the 23th, so the documentation was already prepared. Anyways, let's go for the correct way without going around on this any longer, and of course thanks for the contribution.

**Comment by kelvzxu** [comment]
Terima kasih banyak!

**Comment by kelvzxu** [comment]
i have made a new pull request according to the migration documentation which is from branch 15.0-mig-account_reconcile_widget #436

**Comment by pedrobaeza** [comment]
I still don't see the commit history. Have you followed migration guide? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by kelvzxu** [comment]
yes. I've done it and I've created a new pull request #436

**Comment by kelvzxu** [comment]
yes. I've done it and I've created a new pull request

**Pull request closed without merging**
