### PR TITLE
[ADD] account_bank_statement_unreconcile_line

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is this needed? Odoo already allows this? Or are you talking about undoing when the statement has been closed?

**Comment by hbrunn** [comment]
via the ui, you can only cancel the whole statement. That's annoying for statements containing a lot of lines and you made a mistake in the (n-1)st line

**Comment by pedrobaeza** [comment]
But you have the yellow arrow to make this...

**Comment by hbrunn** [comment]
in the widget?

**Comment by pedrobaeza** [comment]
I mean in the form view:

sin nombre

**Comment by hbrunn** [comment]
oh, I've never seen that. Which module adds it?

**Comment by pedrobaeza** [comment]
It is added by _account_cancel_ standard module: https://github.com/odoo/odoo/blob/8.0/addons/account_cancel/account_cancel_view.xml#L46

**Comment by hbrunn** [comment]
thanks a lot, and sorry for the noise. Cancelled.

**Pull request closed without merging**
