### PR TITLE
Fix accents in fr.po for base_completion_module

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by yvaucher** [comment]
https://code.launchpad.net/~camptocamp/banking-addons/bank-statement-reconcile-7.0-fix-fr-completion-module/+merge/223740

:+1: :+1:  on launchpad already

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
@pedrobaeza please do NOT merge on GitHub!
The branches are still owned by Launchpad and merging on GitHub will break the sync!
I thought I have been clear on the community mailing list.

**Comment by pedrobaeza** [comment]
Sorry, I thought that the switch was made, and the sync can be made bi-directional.

**Comment by guewen** [comment]
On Mon, Jun 30, 2014 at 10:18 AM, Pedro M. Baeza
notifications@github.com wrote:

> Sorry, I thought that the switch was made, and the sync can be made bi-directional.

Hopefully no commit has been done on the Launchpad project meantime. I
suggest you to take care of the migration for this project before a
commit is done on Launchpad so we won't have concurrent commits
(register you as responsible on
https://docs.google.com/spreadsheets/d/1CfGY7rc60jnpAWvMfNf0pI7fBDAlumwI2jx6f_RJ4_4/edit#gid=0)

**Pull request merged**
