### PR TITLE
[14.0][MIG] account_mass_reconcile_by_sale_line

### PR DESCRIPTION
**Pull request by dnplkndll**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @dnplkndll can you include this commit? https://github.com/OCA/account-reconcile/pull/438/commits/8eda175b5bdf49640171ac0b62050bb7af2e1616
I tried to create a PR to your fork but was not able to do so, that is why I created this other PR https://github.com/OCA/account-reconcile/pull/438/ I can close it if consider my changes.

The reason is the sale order for kits fail to reconcile because the product is different in the journal items, I think it is still safe, because the sale order line already has the product on it.

**Comment by dnplkndll** [comment]
@AaronHForgeFlow got it and gave you access.

**Comment by AaronHForgeFlow** [comment]
@dnplkndll Thank you!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
