### PR TITLE
[14][MIG] account_move_so_import

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard migration
Depends on https://github.com/OCA/account-reconcile/pull/373

### CODE REVIEW

**Comment by rvalyi** [comment]
@florian-dacosta at the time you will read that #373 should be merged. So if you could rebase...

**Comment by rvalyi** [comment]
ping @florian-dacosta #373 is merged

**Comment by sonhd91** [comment]
Hi, It's took a while from the last update of this PR, here is some update base on this migrate, [PR#426](https://github.com/OCA/account-reconcile/pull/426), ready for review , please check it out

**Comment by florian-dacosta** [comment]
I close, Pr is replaced by https://github.com/OCA/account-reconcile/pull/426

**Pull request closed without merging**
