### PR TITLE
[10.0]base_transaction_id: reconciliation process should not be restricted to payable and receivable accounts

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
My customer wants to 2 reconcile 2 bank accounts.

- one account to pay the invoice or pos_order
- the other one wen he gets back the money for the payment platform

Whe he imports the bank statement, he would like to reconcile the first one with the second one.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@yvaucher Any opinion on that ? Thanks

**Comment by yvaucher** [comment]
@Cedric-Pigeon This was added when I migrated the module to Odoo 9.0 [1]. I don't know how that module evolved since.

On a functional side, better to ask @fclementic2c my memory is blurry about it.

I don't remind why we wanted only payable or recevable in case there is no partner defined on the statement line.

And I'm not sure what implies your case with 2 bank accounts. (not done a lot of accounting dev lately)


[1] https://github.com/OCA/account-reconcile/pull/127/commits/3d5e954886d0bd076008d01807248aae1b8d76a2

**Comment by fclementic2c** [comment]
I agree. Only reconcilable accounts make sense. I guess we restricted for performance reasons

**Comment by Cedric-Pigeon** [comment]
@fclementic2c @yvaucher could you review/approve this one pls?

**Review by yvaucher — APPROVED** [review]
Not sure to what @fclementic2c agreed here, but code LGTM

**Pull request merged**
