### PR TITLE
[13.0] [MIG] account_reconcile_rule_early_payment_discount

### PR DESCRIPTION
**Pull request by phuctranfxvn**
**Module dependencies:**

- `account_reconcile_rule`: [#354](https://github.com/OCA/account-reconcile/pull/354)
- `account_early_payment_discount`: [#370](https://github.com/OCA/account-payment/pull/370)

### CODE REVIEW

**Comment by leemannd** [comment]
@phuctranerp Could you rebase in order to avoid the conflict on the file `oca_dependencies.txt` ?

**Comment by phuctranfxvn** [comment]
> @phuctranerp Could you rebase in order to avoid the conflict on the file `oca_dependencies.txt` ?

Hi @leemannd

Yes, done
Thanks

**Review by simahawk — COMMENTED** [review]
LG, waiting for dependencies to get merged

**Review by simahawk — APPROVED** [review]

**Comment by grindtildeath** [comment]
Same as for #354 , reconciliation process is broken on the runbot.

**Pull request closed without merging**
