### PR TITLE
[MIG][10.0] base_transaction_id

### PR DESCRIPTION
**Pull request by leemannd**
- Taken previous commits from 9.0 ( translations from Transifex)
- Port of the module

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this already in https://github.com/OCA/bank-statement-reconcile/pull/164?

**Comment by leemannd** [comment]
@pedrobaeza Yep I just saw it in the issue for porting modules. :/
As the other PR is not going forward, should I make a PR with the exact modifications done by @alexis-via ?

**Comment by pedrobaeza** [comment]
Well, the problem with @alexis-via's PRs is that he makes all the changes together, so if he doesn't mind, I prefer that you keep this PR and then he rebases on top, to have smaller PRs to be easier to review.

**Comment by leemannd** [comment]
@pedrobaeza @alexis-via Updated with some changes he has done.

**Comment by lmignon** [comment]
@pedrobaeza @leemannd Sorry but the PR from @alexis-via has been created on Nov 9, 2016! Therefore that's the PR to review and merge once reviewed.

**Comment by pedrobaeza** [comment]
@lmignon, one of the rules is one module by PR, so other PRs have been closed due to that reason.

**Comment by leemannd** [comment]
@lmignon You are absolutely right and @pedrobaeza also. I'm willing to close this PR if the previous one is quickly done (but still in WIP state from early november!) or if @alexis-via is willing to split his PR in order to make it go forehead. I need this module in order to port another module in V10.

**Comment by lmignon** [comment]
@leemannd You can may be help to finalize #164 by fixing the remaining issues and making a PR on #164?

**Comment by leemannd** [comment]
@lmignon For the moment, in this PR there is a correction for the base_transaction_id. It can be cherry-picked (or merged)

**Comment by leemannd** [comment]
Closing as changes have been merged in https://github.com/OCA/bank-statement-reconcile/pull/164

**Pull request closed without merging**
