### PR TITLE
 [12.0][MIG] account_reconcile_rule 

### PR DESCRIPTION
**Pull request by tschanzt**
It seems that since @grindtildeath renamed the module i only have his last commit as a base. Should i try to include the previous ones as well?

### CODE REVIEW

**Comment by grindtildeath** [comment]
~@tschanzt Try to build a new branch using these commands :~
```
git checkout -b 12.0-mig-account_reconcile_rule origin/12.0
git format-patch --keep-subject --stdout origin/12.0..grindtildeath/11.0-mig-account_operation_rule -- account_operation_rule | git am -3 --keep
git format-patch --keep-subject --stdout origin/12.0..grindtildeath/11.0-mig-account_operation_rule -- account_reconcile_rule | git am -3 --keep
git cherry-pick d95a24eea79b3b7e3dabc0b0375bc011f8a3ea7d
```
EDIT: Not sure this is really worth it, as in such case, I ought to bring the commits from #141 in #209 as well. IMO let's just stick to the official OCA guidelines from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch

**Review by p-tombez — COMMENTED** [review]
LG, didn't check JS part as I don't have enough knowledge

**Review by i-vyshnevska — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]
@tschanzt LG :+1: 
Can you add `_description` on `account.reconcile.rule` to make runbot happy ?

**Pull request merged**
