### PR TITLE
fix red travis on 10.0 branch

### PR DESCRIPTION
**Pull request by damdam-s**
https://travis-ci.org/OCA/account-reconcile/jobs/351116736#L1106

### CODE REVIEW

**Comment by damdam-s** [comment]
cc @gurneyalex

**Comment by pedrobaeza** [comment]
Still red I'm afraid

**Comment by damdam-s** [comment]
yep. currency installed by default seems to be USD now ...
tests needs to be adapted according

**Comment by pedrobaeza** [comment]
We have fixed it in other places making the currency change by SQL.

**Comment by pedrobaeza** [comment]
In this case the error is not that one, but using an account that forces to use a secondary currency. Maybe one of your colleagues can help you in fixing it.

**Pull request closed without merging**
