### PR TITLE
[16.0][IMP] account_reconcile_oca: verify data is defined

### PR DESCRIPTION
**Pull request by etobella**
Should fix https://github.com/OCA/account-reconcile/issues/579#issuecomment-1705588449

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can't you prepare data so `line_currency_id` is always filled?

**Comment by etobella** [comment]
The problem might come from old data. If you had this module installed and you reconciled a line previous to the last version, data will not be there. The only option I find is to do this :thinking: migrating the lines might be  hard and expensive for just this... WDYT?

**Comment by pedrobaeza** [comment]
But in any place should be filling `line` dictionary, so I'm talking to fill that value always in that place instead of having to be defensive each time you access data.

**Comment by etobella** [comment]
I understand it, and we are doing that. The problem comes from old data that might have been generated before the inclussion of such data. If you reset and old line, the json might not contain the data :sob:

**Review by pedrobaeza — APPROVED** [review]
OK if there's no other solution. In general, storing intermediate data instead of preparing them on the fly is not a good design choice, but not knowing the details, I can't totally judge.

**Comment by etobella** [comment]
Mmmh, I get your point @pedrobaeza I will create a second PR fixing it in another way, let's see what's better :smile:

**Pull request closed without merging**
