### PR TITLE
[15.0][MIG] account_reconciliation_widget: Migration

### PR DESCRIPTION
**Pull request by kelvzxu**

### CODE REVIEW

**Comment by kelvzxu** [comment]
hello @pedrobaeza i have made a commit fix

**Comment by pedrobaeza** [comment]
Now it seems correct. Reviewers can do their job since now.

**Comment by kelvzxu** [comment]
hello @pedrobaeza 
i looked at the ci/runbot logs and got the problem:
"Unable to find image 'oca-account-reconcile:820a758_env_1_job_1' locally
docker: Error response from daemon: pull access denied for oca-account-reconcile, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'."

how to solve the problem??

**Comment by pedrobaeza** [comment]
runbot is something deprecated in this version. Just use runbo**a**t.

**Comment by kelvzxu** [comment]
Hmm okay
then whether my work is appropriate??

**Comment by pedrobaeza** [comment]
It seems so formally. Now reviewers may do the rest.

**Comment by pedrobaeza** [comment]
Please include #440

**Comment by kelvzxu** [comment]
I have included #440 please review

**Comment by pedrobaeza** [comment]
Tested functionally on runboat and seems to work. Please squash these commits into the other:

Selección_004

**Comment by kelvzxu** [comment]
commit already updated.

**Review by pedrobaeza — APPROVED** [review]

**Comment by kelvzxu** [comment]
@pedrobaeza apakah pull request ini belum di merge

**Comment by pedrobaeza** [comment]
There should be 2 reviews.

**Comment by kelvzxu** [comment]
how can i request a review

**Comment by pedrobaeza** [comment]
You can review other PRs in same repository or other similar ones, and ask in exchange that they review yours.

**Comment by kelvzxu** [comment]
@AaronHForgeFlow can you help review my PRs

**Review by MosabWadea — APPROVED** [review]
I have tested the changes and I can see it working fine.

**Comment by MosabWadea** [comment]
hello @kelvzxu 
can you please review this PR ["Contract PR#795"](https://github.com/OCA/contract/pull/795)

Thanks

**Comment by hitrosol** [comment]
selamat anak medan @kelvzxu 👍

**Pull request merged**
