### PR TITLE
[15.0][MIG] account_move_reconcile_helper

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Review by fuentes73 — APPROVED** [review]

**Comment by ferran-S73** [comment]
Hi @OCA/accounting-maintainers could you review please?

**Comment by thinkwelltwd** [comment]
Could this PR get reviewed / merged? :pray:

**Review by sergiocorato — APPROVED** [review]
Only technical review (not tested)

**Comment by ferran-S73** [comment]
@OCA/accounting-maintainers

**Comment by ferran-S73** [comment]
@OCA/accounting-maintainers

**Comment by sergiocorato** [comment]
This repo is maintained by @OCA/banking-maintainers

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
