### PR TITLE
[12.0][IMP] base_transaction_id: multiple transaction ref

### PR DESCRIPTION
**Pull request by i-vyshnevska**
do not overwrite ref as there can be few transactions related to
one move

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by yvaucher** [comment]
@i-vyshnevska could you squash the commits and fixups?

**Review by yvaucher — APPROVED** [review]

**Comment by i-vyshnevska** [comment]
@yvaucher squashed

**Comment by yvaucher** [comment]
Travis failed on merge on 

```
count_errors 1
pylint expected errors 0, found 1!
```

I don't know which one.
Trying to fix the `__init__.py` issues in #363

**Comment by yvaucher** [comment]
@i-vyshnevska I just merged #363 can you rebase?

**Comment by leemannd** [comment]
@yvaucher PR rebased

**Pull request closed without merging**
