### PR TITLE
[15.0][MIG] account_reconcile_payment_order: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT36433

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @victoralmau please review

**Review by pedrobaeza — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]
LGTM

**Comment by fgi-inoia** [comment]
Hi there! I'm testing the module in v15 but I don't manage to have an automated suggestion of payment matching. Here is my flow: https://www.awesomescreenshot.com/video/25739038 Do you see anything missing? Thank you!

**Pull request merged**
