### PR TITLE
6.1 Add meta files

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Failing due to pep8 and missing base_scheduler_creator module for account_easy_reconcile

**Comment by yvaucher** [comment]
Is this WIP ?

**Comment by bwrsandman** [comment]
no

**Comment by yvaucher** [comment]
Don't you want to use new travis conf with env ?

**Comment by bwrsandman** [comment]
This PR was made 15 days ago. env wasn't an option then.
OCB doesn't have a 6.1 branch. I see no point in adding env.

**Comment by yvaucher** [comment]
right !

This PR adding basic files is ok. Though this won't be green :-/ and can be greenified in other PR basis will be there.

Let accept this.
:+1:

**Pull request merged**
