### PR TITLE
[10.0] Port base modules to v10

### PR DESCRIPTION
**Pull request by alexis-via**
This is a work in progress... it doesn't work yet, because I don't know how to port "self._fields[k]._symbol_set" to v10, cf file account_move_base_import/models/account_move.py method _prepare_insert()

### CODE REVIEW

**Comment by alexis-via** [comment]
Account_move_base_import and base_transaction_id should work fine on v10 with my latest commit dated Nov 13.

**Comment by lmignon** [comment]
@alexis-via Can you check to the errors on travis?

**Comment by leemannd** [comment]
@alexis-via If you cherry-pick from https://github.com/OCA/bank-statement-reconcile/pull/165 you will remove an error related to base_transaction_id

**Comment by leemannd** [comment]
@lmignon @pedrobaeza The error is related to missing workflow imported here https://github.com/OCA/bank-statement-reconcile/blob/10.0/account_move_base_import/test/refund.yml#L30 Just a question, these tests should be updated no?

**Comment by alexis-via** [comment]
I don't plan to work on this PR in the short term (too much work, other priorities). I'll just merge the PR that I may receive. I you prefer to override it with another PR, no pb. It's just a pity to duplicate the porting work... but now that it's done, let's move forward.

**Comment by leemannd** [comment]
@lmignon A [PR](https://github.com/akretion/bank-statement-reconcile/pull/1) on the @alexis-via 's branch has been done to update this.

**Review by leemannd — APPROVED** [review]
Code review

**Comment by ghost** [comment]
Hi guys, what's the state of this PR? Is there still work to do? Otherwise, I suggest you merge it.

**Comment by ghost** [comment]
@leemannd Hi leemannd, maybe you didn't see my last message. Is there still work to do for this PR? If not, I suggest you merge it. There are other PRs like https://github.com/OCA/l10n-switzerland/pull/295 which are waiting for this one.

**Comment by leemannd** [comment]
@BT-faebi Hello, I'm not the initial worker on this PR and nor a PSC member. I made what I could to correct it. I suggest you to make a code review and give a feedback if it's missing something. It would help in the process of merging it.

**Review by guewen — APPROVED** [review]

**Comment by ghost** [comment]
@leemannd I can only give my opinion on the code related to base_transaction_id (as I've never used account_move_base_import). But the code of base_transaction_id looks OK to me.

BTW, in the future it would be good to separate PRs by module, especially in this particular case where base_transaction_id and account_move_base_import are not depending on each other.

**Pull request merged**
