### PR TITLE
[11.0][ADD] account_set_reconcilable

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Account Set Reconcilable
========================

Allows to set as reconcilable a non reconcilable account that already have journal items.

### CODE REVIEW

**Comment by mreficent** [comment]
@jbeficent

**Comment by JordiBForgeFlow** [comment]
@mreficent Can you add tests? Once it's merged we'll need to backport to 10.0

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on runbot and code review LGTM

**Comment by JordiBForgeFlow** [comment]
@mreficent can you backport to 10.0?

**Comment by MiquelRForgeFlow** [comment]
Done in https://github.com/OCA/account-reconcile/pull/225.

**Pull request merged**
