### PR TITLE
[11.0][ADD] account_skip_bank_reconciliation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Account Skip Bank Reconciliation
================================

This module allows to exclude from bank statement reconciliation
all journal items of a specific reconcilable account.

Usually, you would want to that in accounts like the
_Goods Received Not Invoiced_, which are required to be reconcilable
to be able to have proper traceability in stock received but
their reconciliation is done using the `account_mass_reconcile` module.

### CODE REVIEW

**Comment by mreficent** [comment]
@jbeficent

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by CasVissers-360ERP** [comment]
Great module, thanks.

**Comment by CasVissers-360ERP** [comment]
@mreficent Any plans to migrate this module to v12?

**Comment by MiquelRForgeFlow** [comment]
@CasVissers done in https://github.com/OCA/account-reconcile/pull/288.

**Pull request merged**
