### PR TITLE
[16.0][IMP] account_reconcile_oca: Add fields to account.account.reconcile search view

### PR DESCRIPTION
**Pull request by victoralmau**
Add fields to account.account.reconcile search view

ejemplo

Please @pedrobaeza can you review it?

@Tecnativa TT49665

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't see this very useful, except for your current debugging case. Do you, @etobella ?

**Comment by etobella** [comment]
Well, this is something I missed at some point, so I don't see the problem of adding it :thinking:

**Review by pedrobaeza — APPROVED** [review]
OK then

**Review by etobella — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
