### PR TITLE
7.0 Add meta files

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Failing due to pep8 and absence of account_default_draft_move for account_statement_cancel_line

**Comment by bwrsandman** [comment]
Failing due to dependency: `ofxparse`
I don't have time to investigate, but if someone would like to let me know where and how to get it, either post it here of do an MP to my branch.

**Comment by pedrobaeza** [comment]
Hi, Sandy, you can install it with:

`sudo pip install ofxparse`

**Comment by yvaucher** [comment]
TypeError: argument must be 9-item sequence, not datetime.datetime

This can be fixed in another PR

Otherwise :+1:

**Pull request merged**
