### PR TITLE
[IMP] account_statement_base_import: Fill balance start when parser doesn't filled it

### PR DESCRIPTION
**Pull request by pedrobaeza**
Get starting balance from journal balance if parser doesn't fill this data, simulating the manual flow

### CODE REVIEW

**Comment by oihane** [comment]
:+1:

**Comment by lmignon** [comment]
Hi,

it would be nice to have a test that covers this change

lmi

**Comment by pedrobaeza** [comment]
Yeah, but to have it, we have to build full tests, and this is so much work for only this change. Next focus for OCA maintainers when we finish GitHub migration would be this, but for now, we must go on with this little details.

Regards.

**Comment by lmignon** [comment]
I know but I'v already done part of the work by writing test_base_import.py ....

**Comment by pedrobaeza** [comment]
OK, I'll do it on following PRs, but not now, because I don't have time to do it, with all PEP8 issues to solve. I hope you understand.

Regards.

**Comment by lmignon** [comment]
:+1:  Yes I understand.

**Comment by pedrobaeza** [comment]
OK, I proceed with this merge, and next PR is PEP8 fix for this repository.

Stay tuned :wink:

**Pull request merged**
