### PR TITLE
8.0 pep8 v7 forward port

### PR DESCRIPTION
**Pull request by lmignon**
forward port 7.0 into 8.0 after merge of https://github.com/OCA/bank-statement-reconcile/pull/31

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
GitHub has had an error, and this PR has been merged, but not marked as merged, so I close it.

**Pull request closed without merging**
