### PR TITLE
[12.0][MIG] account_mass_reconcile

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Migration of module account_mass_reconcile to v12

### CODE REVIEW

**Review by grindtildeath — COMMENTED** [review]
Looks good, thanks ! :+1: 

Can you just fix this icon ? https://github.com/OCA/account-reconcile/pull/235/commits/dc0973a6ac726e48c12b5e3c87558d15751f6e7a#diff-8ff84e574ea4ebeff6b0c36608d3930aR84

image

**Comment by AdriaGForgeFlow** [comment]
> Looks good, thanks ! 
> 
> Can you just fix this icon ? [dc0973a#diff-8ff84e574ea4ebeff6b0c36608d3930aR84](https://github.com/OCA/account-reconcile/commit/dc0973a6ac726e48c12b5e3c87558d15751f6e7a#diff-8ff84e574ea4ebeff6b0c36608d3930aR84)
> 
> image

Done :+1:

**Review by grindtildeath — APPROVED** [review]

**Comment by tbaden** [comment]
@ageficent cant find the menu metioned in readme unless I install the module account_accountant which is no longer a community module. Maybe another module can fix this as well, but in the runbot instance there is no such menu.

Bildschirmfoto 2019-04-11 um 11 23 14
Bildschirmfoto 2019-04-11 um 11 23 06

**Comment by AdriaGForgeFlow** [comment]
> @ageficent cant find the menu metioned in readme unless I install the module account_accountant which is no longer a community module. Maybe another module can fix this as well, but in the runbot instance there is no such menu.


Indeed the menu is not there. I have updated now the readme.
In order to access the Automatic Mass Reconcile you need first to give to the user the permissions to see the full accounting features and then go to Invoicing / Accounting.

image

Thanks :+1:

**Review by tbaden — APPROVED** [review]
https://github.com/OCA/account-reconcile/blob/c30b739e7293ff506c578ecfdde515eb2a51fd7d/account_mass_reconcile/models/__init__.py#L1-L7

cosmetical change:
sort alphabetically

**Comment by grindtildeath** [comment]
@ageficent 
If you still have some time on this mig, I'm wondering if we could include #253 in this base module instead of having two separated module ?

**Pull request merged**
