### PR TITLE
[16.0] [MIG] account_mass_reconcile: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @sonhd91 could you review and base your work on the 15.0 migration?
Maybe you could use https://github.com/OCA/oca-port . It allows you to easily port modules and take in account open PRs

**Comment by sonhd91** [comment]
> Hello @sonhd91 could you review and base your work on the 15.0 migration? Maybe you could use https://github.com/OCA/oca-port . It allows you to easily port modules and take in account open PRs

Hello, it's now base on 15.0 version, please check again

**Review by leemannd — APPROVED** [review]
Merci

**Review by StephaneMangin — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
