### PR TITLE
[16.0][IMP] account_statement_base: Add statement form view

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

ping @carlosdauden @carolinafernandez-tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is the same as #647

**Comment by sergio-teruel** [comment]
Sorry, I did not see that.
Also I add a smart button to access to lines

**Review by carlosdauden — APPROVED** [review]

**Review by carolinafernandez-tecnativa — APPROVED** [review]
LGTM Thanks :)

**Comment by sergio-teruel** [comment]
PR related: https://github.com/odoo/odoo/pull/167224

**Comment by pedrobaeza** [comment]
@SergioBustamanteFL is it OK for you to go on with this one?

**Comment by sergiobstoj** [comment]
@pedrobaeza yes let's go with this one.. I'll be adapting 2 other PRs of mine that depends on [!647](https://github.com/OCA/account-reconcile/pull/647) to make them dependent on this PR.

**Comment by pedrobaeza** [comment]
Great, thanks:

/ocabot merge minor

Please fw-port it to v17

**Pull request merged**
