### PR TITLE
[16.0][FIX] account_mass_reconcile: New environment is initialized when ...

### PR DESCRIPTION
**Pull request by sergiobstoj**
New environment is initialized when the for loop begins so as not to lose the record of last reconciled items by having "commit_every" > 0 configured.

When having `reconciliation_commit_every` configured as >0
image

There are no records linked on **Display items reconciled on the last run**
image

With this fix, having same config (pictures from this PR Runboat):
image

We can see the las reconciled items:
image

### CODE REVIEW

**Review by aritzolea — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Comment by sergiocorato** [comment]
@AaronHForgeFlow is it possible to merge this one?

**Comment by sergiobstoj** [comment]
@pedrobaeza is ok for merge?

**Comment by pedrobaeza** [comment]
You have to rebase and check CI errors.

**Comment by pedrobaeza** [comment]
Maybe it's because of a missing patch (due to upstream changes) that is in https://github.com/OCA/account-reconcile/pull/762/files#diff-da3dd7506c5308876f8215b711ebc95dca02516bd0a7b61d04d91b2836de9b12R1002

**Pull request merged**
