### PR TITLE
[17.0][IMP] account_reconcile_oca: Add validation for applicability of analytic plans

### PR DESCRIPTION
**Pull request by BernatObrador**
This PR adds validation for the applicability of analytic plans, ensuring that mandatory plans or accounts requiring analytic imputations are properly validated.

The `validate_analytic` context is used in the analytic mixin to validate the applicability of analytic plans when generating analytic lines.

cc https://github.com/APSL 164854

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @ppyczko please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add more context, as the code is not easy to be interpreted

**Comment by BernatObrador** [comment]
Hi, @pedrobaeza! I was writing it, sorry! Now you can review it with the context of the improvement!

**Comment by pedrobaeza** [comment]
Next time please do that in one shot, and that context should be also in the expanded message commit, not only in the PR. Please add it.

**Comment by pedrobaeza** [comment]
Apart from that, as you are doing another bugfix, that should be in a separate commit with its explanation.

**Comment by BernatObrador** [comment]
@pedrobaeza Thanks for your time! Will do the changes now!

**Comment by pedrobaeza** [comment]
You can add here the other bugfix, but in a separate commit.

**Comment by BernatObrador** [comment]
@pedrobaeza I've done that in another PR! Here i'ts: #765

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Well, 2 different commits don't mean 2 different PRs, but don't worry, you can leave it this way now. Just take it into account for the next time if you want to save one PR, but it's not bad at all, as each one can be handled on their own times.

**Comment by BernatObrador** [comment]
@pedrobaeza, I’ll take it from here! Really appreciate your time and help!

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please backport it to 16

**Pull request merged**
