### PR TITLE
[14.0][FIX] account_reconcile_widget : Fix generated reconcile proposal

### PR DESCRIPTION
**Pull request by TeoGoddet**
- fix the value on wich the regex is matched (search on payment_ref instead of name)

### CODE REVIEW

**Comment by TeoGoddet** [comment]
Fixes #404 

With this comment https://github.com/OCA/account-reconcile/pull/359#issuecomment-773409956 on #359 i understood that the error is from the 13 to 14 change made on statement lines (name -> payment_ref)

**Comment by pedrobaeza** [comment]
Please provide a pull request for each of the 3 things, as some of them are very straight. but not others.

**Comment by TeoGoddet** [comment]
Hi ! Is it small enough ?

**Comment by pedrobaeza** [comment]
I still see 2 changes, and I don't understand the decimal separator one. If you leave the other, I will fast-track it, and then we can discuss about the other in a new PR.

**Comment by TeoGoddet** [comment]
Ok, I let only the first change
 let's discuss the decimal separator on #420

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this one as the recurring `name`>`payment_ref` bug:

/ocabot merge patch

**Pull request merged**
