### PR TITLE
[16.0][ADD] module account_move_line_reconcile_manual

### PR DESCRIPTION
**Pull request by alexis-via**
For those like me nostalgic of the good old reconcile wizard that existed up to Odoo v11 in the **account** module. Super fast, super easy.

If balanced:
sshot_full_rec

If not balanced:
sshot_partial_rec

Reconcile with write-off:
sshot_rec_writeoff

### CODE REVIEW

**Comment by legalsylvain** [comment]
@etobella

**Comment by alexis-via** [comment]
After some digging on the error message of pre-commit
```
(readme/DESCRIPTION.rst:7: [E7901(rst-syntax-error), ]  Unexpected indentation.)
```
I think that my rst file is correct ; the problem is in the OCA CI system.

**Comment by alexis-via** [comment]
If someone finds the problem, that's great. Otherwise, I'll remove the **alt** from the images. Not good for blind people, but good for the OCA CI :-(

**Comment by legalsylvain** [comment]
Try this ? https://github.com/akretion/account-reconcile/pull/3

**Comment by alexis-via** [comment]
Thank you very much @legalsylvain

**Review by mourad-ehm — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
