### PR TITLE
account_operation_rule: Migration V9

### PR DESCRIPTION
**Pull request by cyrilgdn**
Was account_statement_operation_rule in V8 but uses "account.statement.operation.template" which was renamed "account.operation.template" in Odoo 9.

### CODE REVIEW

**Comment by moylop260** [comment]
Could you check the following check?
`account_operation_rule/__openerp__.py:7: [C8101(manifest-required-author), ] Missing author required "Odoo Community Association (OCA)" in manifest file`
https://travis-ci.org/OCA/bank-statement-reconcile/jobs/130778092#L436

**Comment by guewen** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by cyrilgdn** [comment]
I added a new commit to fix a bug encountered while testing.

**Comment by jgrandguillaume** [comment]
Looks great, functional test ok ! Thanks for the contribs :+1:

**Pull request merged**
