### PR TITLE
[16.0] [IMP] account_reconcile_oca

### LINKED ISSUE #572: [16.0] notes filed missing from the new reconciliation widget: account_reconcile_oca
**Is your feature request related to a problem?**
I would like to see the "Notes" fields as well, while doing the reconciliation. The notes field is missing from the new reconciliation widget: https://github.com/OCA/account-reconcile/tree/16.0/account_reconcile_oca
Screenshot 2023-08-15 at 18 40 13

**Describe the solution you'd like**
I would like be able to change the fields. Please activate this small tool on the view:
Screenshot 2023-08-15 at 18 35 45

**Describe alternatives you've considered**
If there would be an option at the settings, to active this filed on the left side, on the list: I believe it would work fine. I am open for other suggestions.

**Additional context**
Please do apologise if I am missing something and this feature already exists.

### LINKED ISSUE #586: [16.0] account_reconcile_oca Amount field UoM-Currency is incorrect
## Module
account_reconcile_oca

## Describe the bug
Displaying the statement line of the bank in foreign currency, the "Amount" field shows the incorrect currency. The figure itself gets populated correctly. It is the unit of measurement which is incorrect.

**Expected behavior**

**Additional context**
It is a minor thing. Can You reopen and add it to PR577 ?

Screen Shot 2023-09-06 at 16 00 49

### PR DESCRIPTION
**Pull request by etobella**
Fix #586 
Implements #572

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by etobella** [comment]
@nagybal Can you test it please :pray: ?

**Comment by nagybal** [comment]
I can confirm, the currency shows OK.

The translations are better now.
- Unreconcile OK
- "Reset reconciliation" is better than "Undo reconciliation". (If it is not too much coding, I would add a mouseover-hovering text box with clarification)

**Comment by pedrobaeza** [comment]
Wasn't finally "Unreconcile" the selected word?

**Review by marcelsavegnago — APPROVED** [review]

**Comment by nagybal** [comment]
About showing the right currency I did find a similar minor display issue, where the UoM of the currency is incorrect:
If You issue an invoice there is a specific exchange rate, one month later of course it is not the same exchange rate. The validation tool is smart enough and is adding the "976000 Exchange rate gains on exchange and valuation". This working as expected but as you see, its adding the difference again in the wrong currency. The amount is correct by the way:
Screenshot 2023-09-08 at 16 19 12

I did find a bug as well. Every time I click the second line. Marked with blue on the screenshot. The reconciliation tool adds an other line. Why it is happening I do not understand.
Screenshot 2023-09-08 at 16 29 24

**Comment by nagybal** [comment]
I was able to reproduce this on runboat as well
Screenshot 2023-09-09 at 6 59 09


And the strange extra lines on click
Screenshot 2023-09-09 at 6 59 26

**Pull request merged**
