### PR TITLE
[9.0][FIX] issue with mass_reconcile

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fix issue https://github.com/OCA/account-reconcile/issues/188.

cc: @jbeficent @florian-dacosta

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Thank you for looking into it!
I don't see how it fix it though, I think, we should replace `self.env["mass.reconcile.base"]._base_columns()` by `self._base_columns()` in account_mass_reconcile/models/base_reconciliation.py at line 68

**Review by LoisRForgeFlow — APPROVED** [review]
Tested, works ok :+1:

**Review by florian-dacosta — APPROVED** [review]
Thanks for the fix
I did test with account_mass_reconcile_transaction_ref module but not account_mass_reconcile_by_purchase_line

**Comment by LoisRForgeFlow** [comment]
@florian-dacosta FYI my tests were with 'account_mass_reconcile_by_purchase_line' so I think everything works ok now :smile:

**Comment by florian-dacosta** [comment]
Yes, That is what I thought :)

**Pull request merged**
