### PR TITLE
[WIP] 10.0 mig account move transactionid import

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about #164 ?

**Comment by damdam-s** [comment]
@pedrobaeza #164 has been merged but the migration of this module was not done inside. just announced

**Comment by pedrobaeza** [comment]
OK, thanks for specifying. Can you please squash adjacent "OCA Transbot..." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?

**Comment by damdam-s** [comment]
of course :smile:

**Comment by PierrickBrun** [comment]
Tests are failing on invoice.yml L20 which uses the old 'workflow' keyword. This shouldn't be hard to fix.

LGTM otherwise, made it run without problems

**Pull request closed without merging**
