### PR TITLE
[ADD] Add account_statement_partner_lines module

### PR DESCRIPTION
**Pull request by adrienpeiffer**
This module was written to allow you to see and select partner's move lines from bank statement reconcile widget

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't really see the advantage of this module over the default move line selection. Can you point me the purpose of it?

**Comment by adrienpeiffer** [comment]
Hi @pedrobaeza ,
The main feature of this module is to see partner's move line to have a global vision on them.
Regarding the functionnality for select move line to add on the reconciliation, there is no real advantage.

**Comment by pedrobaeza** [comment]
Isn't better to have a button next to the proposition lines to unfold all possible move lines? This will look more consistent with current UI and with the same effectiveness

**Comment by pedrobaeza** [comment]
No answer, so closing. Feel free to reopen if needed.

**Pull request closed without merging**
