### PR TITLE
Regression fix for #79

### PR DESCRIPTION
**Pull request by ecino**
- Fix error logs that tried to access inexistant attribute.

### CODE REVIEW

**Comment by guewen** [comment]
ping @mdietrichc2c

**Comment by mdietrichc2c** [comment]
LGTM (it's true that Exception doesn't have a 'value' attribute).
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
Oups, it was not correct. An Exception has only 1 item in `args`.

``` python
>>> Exception('test')[1]
IndexError: tuple index out of range
```

`orm.except_orm` has 2 items (the title and the message).
Maybe the simplest is just to show all the args, maybe concatenating them with a join.

**Comment by yvaucher** [comment]
Done in #89

**Pull request merged**
