### PR TITLE
[17.0][IMP] account_reconcile_oca: Use receivable/payable account on statements with partner as suspense account

### PR DESCRIPTION
**Pull request by etobella**
With this change, it sets the proper account automatically

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by etobella** [comment]
It was not actually a problem. With the original solution, if I add a new statement.line related to a partner, the suspense account will be the suspense account of the Journal. With the new change, in this case will get the right receivable or payable account of the partner.

It is the behavior we had on 15 and Odoo is promoting on EE

**Review by pedrobaeza — APPROVED** [review]
OK, not sure the gain with this move, but it's not the usual case anyway.

**Comment by etobella** [comment]
Well, it is how it worked and we lost that functionality from reconcile_widget to account_reconcile_oca. Someone noticed and I made the change because it wasn't too much :smile:

**Comment by pedrobaeza** [comment]
Yeah, now I see:

Peek 2024-08-01 09-08

but it was so insignificant, as that old line doesn't serve for anything if you don't click or manually create a line. What I miss is to have the suspense line as grey to know that "you have to do an action".

**Comment by JordiBForgeFlow** [comment]
I agree with @pedrobaeza. In enterprise the account stays as suspense account, but from a UI perspective it shows the receivable/payable. Weird.

But it's not a problem to show the suspense account because when reconciling with a line, it will be changed right? Perhaps the issue is when you don't want to reconcile with a line but keep the amount in the default partner receivable/payable account. Then you must remember this account.

**Comment by pedrobaeza** [comment]
@etobella can you rebase?

**Pull request merged**
